services:
  web:
    container_name: web_container
    image: httpd
    ports:
      - "80:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    depends_on:
      - fluentd

  fluentd:
    container_name: fluentd_container
    build: docker/fluentd
    volumes:
      - ./docker/fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch_container
    build: docker/elasticsearch
    env_file:
      - .env
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana_container
    image: kibana:8.15.2
    ports:
      - "5601:5601"

volumes:
  esdata: